# CDLD training for microbial coculture prediction

Train the discovery models and prediction models, select models using validation data, and evaluate performance across training-data fractions. The cells use the model code and data splits in full/ and fractions/.
Run 00_Prepare_Data.ipynb first. Outputs are generated when this source notebook is executed.

In [1]:
from pathlib import Path
import os,sys,json,time,subprocess,concurrent.futures,platform
R=Path.cwd();assert (R/'full/primary/model.py').exists()
assert platform.system()=='Darwin', 'This run is designated macOS reproduction'
SEEDS=[17,43,101,137,211]
def run(args):
 env=os.environ.copy();env.update(OMP_NUM_THREADS='2',OPENBLAS_NUM_THREADS='2',VECLIB_MAXIMUM_THREADS='2')
 tag='_'.join(str(x).replace('/','_') for x in args)[-170:];logs=R/'logs';logs.mkdir(exist_ok=True)
 with (logs/(tag+'.log')).open('a') as f:
  subprocess.run([sys.executable,*map(str,args)],cwd=R,env=env,stdout=f,stderr=subprocess.STDOUT,check=True)
 return tag
def batch(jobs,label):
 print(label, 'jobs:',len(jobs),flush=True)
 with concurrent.futures.ThreadPoolExecutor(max_workers=4) as pool:
  futures=[pool.submit(run,j) for j in jobs]
  for k,f in enumerate(concurrent.futures.as_completed(futures),1):
   tag=f.result();print(label,k,'/',len(jobs),tag,flush=True)
   (R/'status.json').write_text(json.dumps(dict(phase=label,completed=k,total=len(jobs),updated=time.time())))

In [2]:
batch([[R/'full'/sp/'run_job.py','source','gm',s,'source'] for sp in ['primary','robust'] for s in SEEDS], '24h_discovery')

24h_discovery jobs: 10

24h_discovery 1 / 10 full_primary_run_job.py_source_gm_101_source

24h_discovery 2 / 10 full_primary_run_job.py_source_gm_17_source

24h_discovery 3 / 10 full_primary_run_job.py_source_gm_43_source

24h_discovery 4 / 10 full_primary_run_job.py_source_gm_137_source

24h_discovery 5 / 10 full_robust_run_job.py_source_gm_43_source

24h_discovery 6 / 10 full_primary_run_job.py_source_gm_211_source

24h_discovery 7 / 10 full_robust_run_job.py_source_gm_17_source

24h_discovery 8 / 10 full_robust_run_job.py_source_gm_101_source

24h_discovery 9 / 10 full_robust_run_job.py_source_gm_137_source

24h_discovery 10 / 10 full_robust_run_job.py_source_gm_211_source

In [3]:
batch([[R/'full'/sp/'run_job.py','reader','gm',s,t] for sp in ['primary','robust'] for t in ['hour48','trio'] for s in SEEDS]+[[R/'full/primary/run_job.py','aug','gm',s,'source'] for s in SEEDS], 'full_predictors')

full_predictors jobs: 25

full_predictors 1 / 25 full_primary_run_job.py_reader_gm_17_hour48

full_predictors 2 / 25 full_primary_run_job.py_reader_gm_101_hour48

full_predictors 3 / 25 full_primary_run_job.py_reader_gm_43_hour48

full_predictors 4 / 25 full_primary_run_job.py_reader_gm_137_hour48

full_predictors 5 / 25 full_primary_run_job.py_reader_gm_211_hour48

full_predictors 6 / 25 full_primary_run_job.py_reader_gm_17_trio

full_predictors 7 / 25 full_primary_run_job.py_reader_gm_101_trio

full_predictors 8 / 25 full_primary_run_job.py_reader_gm_43_trio

full_predictors 9 / 25 full_robust_run_job.py_reader_gm_17_hour48

full_predictors 10 / 25 full_primary_run_job.py_reader_gm_137_trio

full_predictors 11 / 25 full_robust_run_job.py_reader_gm_43_hour48

full_predictors 12 / 25 full_primary_run_job.py_reader_gm_211_trio

full_predictors 13 / 25 full_robust_run_job.py_reader_gm_137_hour48

full_predictors 14 / 25 full_robust_run_job.py_reader_gm_101_hour48

full_predictors 15 / 25 full_robust_run_job.py_reader_gm_211_hour48

full_predictors 16 / 25 full_robust_run_job.py_reader_gm_17_trio

full_predictors 17 / 25 full_robust_run_job.py_reader_gm_137_trio

full_predictors 18 / 25 full_robust_run_job.py_reader_gm_43_trio

full_predictors 19 / 25 full_robust_run_job.py_reader_gm_211_trio

full_predictors 20 / 25 full_robust_run_job.py_reader_gm_101_trio

full_predictors 21 / 25 full_primary_run_job.py_aug_gm_43_source

full_predictors 22 / 25 full_primary_run_job.py_aug_gm_137_source

full_predictors 23 / 25 full_primary_run_job.py_aug_gm_17_source

full_predictors 24 / 25 full_primary_run_job.py_aug_gm_101_source

full_predictors 25 / 25 full_primary_run_job.py_aug_gm_211_source

In [4]:
batch([[R/'full/baselines.py',R/'full/primary']], 'primary_baselines')
batch([[R/'full/baselines.py',R/'full/robust']], 'robust_baselines')

primary_baselines jobs: 1

primary_baselines 1 / 1 baselines_full_primary

robust_baselines jobs: 1

robust_baselines 1 / 1 baselines_full_robust

In [5]:
items=json.loads((R/'fractions/subsets.json').read_text())
# 100% LF is fitted again to verify the adapter's validation predictions.
batch([[R/'fractions/train.py','q100_r00','LF',s,'reader'] for s in SEEDS], '100pct_gate')
import numpy as np
for s in SEEDS:
 a=np.load(R/f'full/primary/runs/reader_hour48_gm_{s}/validation_predictions.npz')
 b=np.load(R/f'fractions/subsets/q100_r00/LF/runs/reader_hour48_initial_{s}/validation_predictions.npz')
 np.testing.assert_array_equal(a['row_id'],b['row_id']);np.testing.assert_allclose(a['prediction'],b['prediction'],rtol=0,atol=1e-7)
print('100% validation gate passed')

100pct_gate jobs: 5

100pct_gate 1 / 5 fractions_train.py_q100_r00_LF_17_reader

100pct_gate 2 / 5 fractions_train.py_q100_r00_LF_101_reader

100pct_gate 3 / 5 fractions_train.py_q100_r00_LF_43_reader

100pct_gate 4 / 5 fractions_train.py_q100_r00_LF_137_reader

100pct_gate 5 / 5 fractions_train.py_q100_r00_LF_211_reader

100% validation gate passed

In [6]:
batch([[R/'fractions/train.py',x['name'],c,s,'source'] for x in items for c in ['LU','RU'] for s in SEEDS], '48h_discovery')

48h_discovery jobs: 310

48h_discovery 1 / 310 fractions_train.py_q010_r00_LU_101_source

48h_discovery 2 / 310 fractions_train.py_q010_r00_LU_43_source

48h_discovery 3 / 310 fractions_train.py_q010_r00_LU_137_source

48h_discovery 4 / 310 fractions_train.py_q010_r00_LU_17_source

48h_discovery 5 / 310 fractions_train.py_q010_r00_LU_211_source

48h_discovery 6 / 310 fractions_train.py_q010_r00_RU_43_source

48h_discovery 7 / 310 fractions_train.py_q010_r00_RU_101_source

48h_discovery 8 / 310 fractions_train.py_q010_r00_RU_17_source

48h_discovery 9 / 310 fractions_train.py_q025_r00_LU_17_source

48h_discovery 10 / 310 fractions_train.py_q025_r00_LU_43_source

48h_discovery 11 / 310 fractions_train.py_q025_r00_LU_101_source

48h_discovery 12 / 310 fractions_train.py_q010_r00_RU_211_source

48h_discovery 13 / 310 fractions_train.py_q025_r00_LU_137_source

48h_discovery 14 / 310 fractions_train.py_q025_r00_LU_211_source

48h_discovery 15 / 310 fractions_train.py_q010_r00_RU_137_source

48h_discovery 16 / 310 fractions_train.py_q025_r00_RU_101_source

48h_discovery 17 / 310 fractions_train.py_q025_r00_RU_43_source

48h_discovery 18 / 310 fractions_train.py_q025_r00_RU_17_source

48h_discovery 19 / 310 fractions_train.py_q025_r00_RU_137_source

48h_discovery 20 / 310 fractions_train.py_q050_r00_LU_43_source

48h_discovery 21 / 310 fractions_train.py_q050_r00_LU_17_source

48h_discovery 22 / 310 fractions_train.py_q050_r00_LU_101_source

48h_discovery 23 / 310 fractions_train.py_q025_r00_RU_211_source

48h_discovery 24 / 310 fractions_train.py_q050_r00_LU_137_source

48h_discovery 25 / 310 fractions_train.py_q050_r00_LU_211_source

48h_discovery 26 / 310 fractions_train.py_q050_r00_RU_43_source

48h_discovery 27 / 310 fractions_train.py_q050_r00_RU_17_source

48h_discovery 28 / 310 fractions_train.py_q050_r00_RU_101_source

48h_discovery 29 / 310 fractions_train.py_q050_r00_RU_137_source

48h_discovery 30 / 310 fractions_train.py_q100_r00_LU_17_source

48h_discovery 31 / 310 fractions_train.py_q100_r00_LU_43_source

48h_discovery 32 / 310 fractions_train.py_q100_r00_LU_101_source

48h_discovery 33 / 310 fractions_train.py_q050_r00_RU_211_source

48h_discovery 34 / 310 fractions_train.py_q100_r00_LU_137_source

48h_discovery 35 / 310 fractions_train.py_q100_r00_LU_211_source

48h_discovery 36 / 310 fractions_train.py_q100_r00_RU_43_source

48h_discovery 37 / 310 fractions_train.py_q100_r00_RU_101_source

48h_discovery 38 / 310 fractions_train.py_q010_r01_LU_17_source

48h_discovery 39 / 310 fractions_train.py_q100_r00_RU_137_source

48h_discovery 40 / 310 fractions_train.py_q010_r01_LU_43_source

48h_discovery 41 / 310 fractions_train.py_q100_r00_RU_17_source

48h_discovery 42 / 310 fractions_train.py_q010_r01_LU_101_source

48h_discovery 43 / 310 fractions_train.py_q010_r01_LU_137_source

48h_discovery 44 / 310 fractions_train.py_q010_r01_LU_211_source

48h_discovery 45 / 310 fractions_train.py_q010_r01_RU_17_source

48h_discovery 46 / 310 fractions_train.py_q100_r00_RU_211_source

48h_discovery 47 / 310 fractions_train.py_q010_r01_RU_43_source

48h_discovery 48 / 310 fractions_train.py_q010_r01_RU_101_source

48h_discovery 49 / 310 fractions_train.py_q025_r01_LU_17_source

48h_discovery 50 / 310 fractions_train.py_q025_r01_LU_43_source

48h_discovery 51 / 310 fractions_train.py_q025_r01_LU_101_source

48h_discovery 52 / 310 fractions_train.py_q010_r01_RU_211_source

48h_discovery 53 / 310 fractions_train.py_q010_r01_RU_137_source

48h_discovery 54 / 310 fractions_train.py_q025_r01_LU_137_source

48h_discovery 55 / 310 fractions_train.py_q025_r01_LU_211_source

48h_discovery 56 / 310 fractions_train.py_q025_r01_RU_17_source

48h_discovery 57 / 310 fractions_train.py_q025_r01_RU_101_source

48h_discovery 58 / 310 fractions_train.py_q025_r01_RU_43_source

48h_discovery 59 / 310 fractions_train.py_q025_r01_RU_137_source

48h_discovery 60 / 310 fractions_train.py_q050_r01_LU_17_source

48h_discovery 61 / 310 fractions_train.py_q050_r01_LU_101_source

48h_discovery 62 / 310 fractions_train.py_q050_r01_LU_137_source

48h_discovery 63 / 310 fractions_train.py_q050_r01_LU_211_source

48h_discovery 64 / 310 fractions_train.py_q050_r01_LU_43_source

48h_discovery 65 / 310 fractions_train.py_q025_r01_RU_211_source

48h_discovery 66 / 310 fractions_train.py_q050_r01_RU_43_source

48h_discovery 67 / 310 fractions_train.py_q050_r01_RU_17_source

48h_discovery 68 / 310 fractions_train.py_q050_r01_RU_137_source

48h_discovery 69 / 310 fractions_train.py_q010_r02_LU_17_source

48h_discovery 70 / 310 fractions_train.py_q010_r02_LU_43_source

48h_discovery 71 / 310 fractions_train.py_q050_r01_RU_101_source

48h_discovery 72 / 310 fractions_train.py_q010_r02_LU_101_source

48h_discovery 73 / 310 fractions_train.py_q010_r02_LU_137_source

48h_discovery 74 / 310 fractions_train.py_q010_r02_LU_211_source

48h_discovery 75 / 310 fractions_train.py_q050_r01_RU_211_source

48h_discovery 76 / 310 fractions_train.py_q010_r02_RU_17_source

48h_discovery 77 / 310 fractions_train.py_q010_r02_RU_101_source

48h_discovery 78 / 310 fractions_train.py_q010_r02_RU_43_source

48h_discovery 79 / 310 fractions_train.py_q025_r02_LU_17_source

48h_discovery 80 / 310 fractions_train.py_q025_r02_LU_43_source

48h_discovery 81 / 310 fractions_train.py_q010_r02_RU_211_source

48h_discovery 82 / 310 fractions_train.py_q010_r02_RU_137_source

48h_discovery 83 / 310 fractions_train.py_q025_r02_LU_101_source

48h_discovery 84 / 310 fractions_train.py_q025_r02_LU_137_source

48h_discovery 85 / 310 fractions_train.py_q025_r02_LU_211_source

48h_discovery 86 / 310 fractions_train.py_q025_r02_RU_43_source

48h_discovery 87 / 310 fractions_train.py_q025_r02_RU_17_source

48h_discovery 88 / 310 fractions_train.py_q025_r02_RU_101_source

48h_discovery 89 / 310 fractions_train.py_q025_r02_RU_137_source

48h_discovery 90 / 310 fractions_train.py_q050_r02_LU_17_source

48h_discovery 91 / 310 fractions_train.py_q050_r02_LU_43_source

48h_discovery 92 / 310 fractions_train.py_q050_r02_LU_101_source

48h_discovery 93 / 310 fractions_train.py_q025_r02_RU_211_source

48h_discovery 94 / 310 fractions_train.py_q050_r02_LU_137_source

48h_discovery 95 / 310 fractions_train.py_q050_r02_LU_211_source

48h_discovery 96 / 310 fractions_train.py_q050_r02_RU_101_source

48h_discovery 97 / 310 fractions_train.py_q050_r02_RU_43_source

48h_discovery 98 / 310 fractions_train.py_q050_r02_RU_17_source

48h_discovery 99 / 310 fractions_train.py_q010_r03_LU_17_source

48h_discovery 100 / 310 fractions_train.py_q010_r03_LU_43_source

48h_discovery 101 / 310 fractions_train.py_q010_r03_LU_101_source

48h_discovery 102 / 310 fractions_train.py_q050_r02_RU_137_source

48h_discovery 103 / 310 fractions_train.py_q010_r03_LU_137_source

48h_discovery 104 / 310 fractions_train.py_q010_r03_LU_211_source

48h_discovery 105 / 310 fractions_train.py_q050_r02_RU_211_source

48h_discovery 106 / 310 fractions_train.py_q010_r03_RU_101_source

48h_discovery 107 / 310 fractions_train.py_q010_r03_RU_137_source

48h_discovery 108 / 310 fractions_train.py_q010_r03_RU_17_source

48h_discovery 109 / 310 fractions_train.py_q010_r03_RU_43_source

48h_discovery 110 / 310 fractions_train.py_q025_r03_LU_43_source

48h_discovery 111 / 310 fractions_train.py_q025_r03_LU_17_source

48h_discovery 112 / 310 fractions_train.py_q025_r03_LU_101_source

48h_discovery 113 / 310 fractions_train.py_q010_r03_RU_211_source

48h_discovery 114 / 310 fractions_train.py_q025_r03_LU_137_source

48h_discovery 115 / 310 fractions_train.py_q025_r03_LU_211_source

48h_discovery 116 / 310 fractions_train.py_q025_r03_RU_17_source

48h_discovery 117 / 310 fractions_train.py_q025_r03_RU_101_source

48h_discovery 118 / 310 fractions_train.py_q025_r03_RU_43_source

48h_discovery 119 / 310 fractions_train.py_q025_r03_RU_137_source

48h_discovery 120 / 310 fractions_train.py_q025_r03_RU_211_source

48h_discovery 121 / 310 fractions_train.py_q050_r03_LU_101_source

48h_discovery 122 / 310 fractions_train.py_q050_r03_LU_17_source

48h_discovery 123 / 310 fractions_train.py_q050_r03_LU_43_source

48h_discovery 124 / 310 fractions_train.py_q050_r03_LU_211_source

48h_discovery 125 / 310 fractions_train.py_q050_r03_LU_137_source

48h_discovery 126 / 310 fractions_train.py_q050_r03_RU_43_source

48h_discovery 127 / 310 fractions_train.py_q050_r03_RU_17_source

48h_discovery 128 / 310 fractions_train.py_q050_r03_RU_137_source

48h_discovery 129 / 310 fractions_train.py_q010_r04_LU_17_source

48h_discovery 130 / 310 fractions_train.py_q050_r03_RU_101_source

48h_discovery 131 / 310 fractions_train.py_q010_r04_LU_43_source

48h_discovery 132 / 310 fractions_train.py_q010_r04_LU_101_source

48h_discovery 133 / 310 fractions_train.py_q050_r03_RU_211_source

48h_discovery 134 / 310 fractions_train.py_q010_r04_LU_211_source

48h_discovery 135 / 310 fractions_train.py_q010_r04_LU_137_source

48h_discovery 136 / 310 fractions_train.py_q010_r04_RU_17_source

48h_discovery 137 / 310 fractions_train.py_q010_r04_RU_101_source

48h_discovery 138 / 310 fractions_train.py_q010_r04_RU_43_source

48h_discovery 139 / 310 fractions_train.py_q010_r04_RU_137_source

48h_discovery 140 / 310 fractions_train.py_q025_r04_LU_17_source

48h_discovery 141 / 310 fractions_train.py_q025_r04_LU_101_source

48h_discovery 142 / 310 fractions_train.py_q025_r04_LU_43_source

48h_discovery 143 / 310 fractions_train.py_q025_r04_LU_137_source

48h_discovery 144 / 310 fractions_train.py_q025_r04_LU_211_source

48h_discovery 145 / 310 fractions_train.py_q010_r04_RU_211_source

48h_discovery 146 / 310 fractions_train.py_q025_r04_RU_17_source

48h_discovery 147 / 310 fractions_train.py_q025_r04_RU_43_source

48h_discovery 148 / 310 fractions_train.py_q025_r04_RU_101_source

48h_discovery 149 / 310 fractions_train.py_q050_r04_LU_17_source

48h_discovery 150 / 310 fractions_train.py_q025_r04_RU_137_source

48h_discovery 151 / 310 fractions_train.py_q025_r04_RU_211_source

48h_discovery 152 / 310 fractions_train.py_q050_r04_LU_43_source

48h_discovery 153 / 310 fractions_train.py_q050_r04_LU_101_source

48h_discovery 154 / 310 fractions_train.py_q050_r04_LU_137_source

48h_discovery 155 / 310 fractions_train.py_q050_r04_LU_211_source

48h_discovery 156 / 310 fractions_train.py_q050_r04_RU_17_source

48h_discovery 157 / 310 fractions_train.py_q050_r04_RU_101_source

48h_discovery 158 / 310 fractions_train.py_q050_r04_RU_43_source

48h_discovery 159 / 310 fractions_train.py_q050_r04_RU_137_source

48h_discovery 160 / 310 fractions_train.py_q010_r05_LU_43_source

48h_discovery 161 / 310 fractions_train.py_q010_r05_LU_17_source

48h_discovery 162 / 310 fractions_train.py_q010_r05_LU_101_source

48h_discovery 163 / 310 fractions_train.py_q010_r05_LU_211_source

48h_discovery 164 / 310 fractions_train.py_q010_r05_LU_137_source

48h_discovery 165 / 310 fractions_train.py_q050_r04_RU_211_source

48h_discovery 166 / 310 fractions_train.py_q010_r05_RU_101_source

48h_discovery 167 / 310 fractions_train.py_q010_r05_RU_17_source

48h_discovery 168 / 310 fractions_train.py_q010_r05_RU_43_source

48h_discovery 169 / 310 fractions_train.py_q010_r05_RU_137_source

48h_discovery 170 / 310 fractions_train.py_q025_r05_LU_17_source

48h_discovery 171 / 310 fractions_train.py_q025_r05_LU_43_source

48h_discovery 172 / 310 fractions_train.py_q025_r05_LU_137_source

48h_discovery 173 / 310 fractions_train.py_q025_r05_LU_101_source

48h_discovery 174 / 310 fractions_train.py_q010_r05_RU_211_source

48h_discovery 175 / 310 fractions_train.py_q025_r05_LU_211_source

48h_discovery 176 / 310 fractions_train.py_q025_r05_RU_43_source

48h_discovery 177 / 310 fractions_train.py_q025_r05_RU_101_source

48h_discovery 178 / 310 fractions_train.py_q025_r05_RU_17_source

48h_discovery 179 / 310 fractions_train.py_q025_r05_RU_137_source

48h_discovery 180 / 310 fractions_train.py_q050_r05_LU_17_source

48h_discovery 181 / 310 fractions_train.py_q025_r05_RU_211_source

48h_discovery 182 / 310 fractions_train.py_q050_r05_LU_43_source

48h_discovery 183 / 310 fractions_train.py_q050_r05_LU_101_source

48h_discovery 184 / 310 fractions_train.py_q050_r05_LU_137_source

48h_discovery 185 / 310 fractions_train.py_q050_r05_LU_211_source

48h_discovery 186 / 310 fractions_train.py_q050_r05_RU_17_source

48h_discovery 187 / 310 fractions_train.py_q050_r05_RU_101_source

48h_discovery 188 / 310 fractions_train.py_q010_r06_LU_17_source

48h_discovery 189 / 310 fractions_train.py_q050_r05_RU_43_source

48h_discovery 190 / 310 fractions_train.py_q010_r06_LU_101_source

48h_discovery 191 / 310 fractions_train.py_q010_r06_LU_43_source

48h_discovery 192 / 310 fractions_train.py_q050_r05_RU_137_source

48h_discovery 193 / 310 fractions_train.py_q050_r05_RU_211_source

48h_discovery 194 / 310 fractions_train.py_q010_r06_LU_211_source

48h_discovery 195 / 310 fractions_train.py_q010_r06_LU_137_source

48h_discovery 196 / 310 fractions_train.py_q010_r06_RU_17_source

48h_discovery 197 / 310 fractions_train.py_q010_r06_RU_43_source

48h_discovery 198 / 310 fractions_train.py_q010_r06_RU_137_source

48h_discovery 199 / 310 fractions_train.py_q010_r06_RU_101_source

48h_discovery 200 / 310 fractions_train.py_q025_r06_LU_17_source

48h_discovery 201 / 310 fractions_train.py_q025_r06_LU_43_source

48h_discovery 202 / 310 fractions_train.py_q025_r06_LU_101_source

48h_discovery 203 / 310 fractions_train.py_q010_r06_RU_211_source

48h_discovery 204 / 310 fractions_train.py_q025_r06_LU_137_source

48h_discovery 205 / 310 fractions_train.py_q025_r06_LU_211_source

48h_discovery 206 / 310 fractions_train.py_q025_r06_RU_101_source

48h_discovery 207 / 310 fractions_train.py_q025_r06_RU_137_source

48h_discovery 208 / 310 fractions_train.py_q025_r06_RU_17_source

48h_discovery 209 / 310 fractions_train.py_q025_r06_RU_43_source

48h_discovery 210 / 310 fractions_train.py_q050_r06_LU_101_source

48h_discovery 211 / 310 fractions_train.py_q050_r06_LU_43_source

48h_discovery 212 / 310 fractions_train.py_q050_r06_LU_17_source

48h_discovery 213 / 310 fractions_train.py_q025_r06_RU_211_source

48h_discovery 214 / 310 fractions_train.py_q050_r06_LU_137_source

48h_discovery 215 / 310 fractions_train.py_q050_r06_LU_211_source

48h_discovery 216 / 310 fractions_train.py_q050_r06_RU_17_source

48h_discovery 217 / 310 fractions_train.py_q050_r06_RU_101_source

48h_discovery 218 / 310 fractions_train.py_q050_r06_RU_43_source

48h_discovery 219 / 310 fractions_train.py_q050_r06_RU_137_source

48h_discovery 220 / 310 fractions_train.py_q010_r07_LU_17_source

48h_discovery 221 / 310 fractions_train.py_q010_r07_LU_43_source

48h_discovery 222 / 310 fractions_train.py_q010_r07_LU_101_source

48h_discovery 223 / 310 fractions_train.py_q050_r06_RU_211_source

48h_discovery 224 / 310 fractions_train.py_q010_r07_LU_137_source

48h_discovery 225 / 310 fractions_train.py_q010_r07_LU_211_source

48h_discovery 226 / 310 fractions_train.py_q010_r07_RU_43_source

48h_discovery 227 / 310 fractions_train.py_q010_r07_RU_17_source

48h_discovery 228 / 310 fractions_train.py_q010_r07_RU_101_source

48h_discovery 229 / 310 fractions_train.py_q010_r07_RU_137_source

48h_discovery 230 / 310 fractions_train.py_q025_r07_LU_43_source

48h_discovery 231 / 310 fractions_train.py_q025_r07_LU_17_source

48h_discovery 232 / 310 fractions_train.py_q010_r07_RU_211_source

48h_discovery 233 / 310 fractions_train.py_q025_r07_LU_101_source

48h_discovery 234 / 310 fractions_train.py_q025_r07_LU_211_source

48h_discovery 235 / 310 fractions_train.py_q025_r07_LU_137_source

48h_discovery 236 / 310 fractions_train.py_q025_r07_RU_17_source

48h_discovery 237 / 310 fractions_train.py_q025_r07_RU_101_source

48h_discovery 238 / 310 fractions_train.py_q025_r07_RU_43_source

48h_discovery 239 / 310 fractions_train.py_q025_r07_RU_137_source

48h_discovery 240 / 310 fractions_train.py_q050_r07_LU_17_source

48h_discovery 241 / 310 fractions_train.py_q050_r07_LU_43_source

48h_discovery 242 / 310 fractions_train.py_q050_r07_LU_101_source

48h_discovery 243 / 310 fractions_train.py_q050_r07_LU_137_source

48h_discovery 244 / 310 fractions_train.py_q025_r07_RU_211_source

48h_discovery 245 / 310 fractions_train.py_q050_r07_LU_211_source

48h_discovery 246 / 310 fractions_train.py_q050_r07_RU_101_source

48h_discovery 247 / 310 fractions_train.py_q050_r07_RU_43_source

48h_discovery 248 / 310 fractions_train.py_q050_r07_RU_17_source

48h_discovery 249 / 310 fractions_train.py_q050_r07_RU_137_source

48h_discovery 250 / 310 fractions_train.py_q010_r08_LU_43_source

48h_discovery 251 / 310 fractions_train.py_q010_r08_LU_17_source

48h_discovery 252 / 310 fractions_train.py_q010_r08_LU_101_source

48h_discovery 253 / 310 fractions_train.py_q010_r08_LU_211_source

48h_discovery 254 / 310 fractions_train.py_q010_r08_LU_137_source

48h_discovery 255 / 310 fractions_train.py_q010_r08_RU_17_source

48h_discovery 256 / 310 fractions_train.py_q010_r08_RU_101_source

48h_discovery 257 / 310 fractions_train.py_q010_r08_RU_43_source

48h_discovery 258 / 310 fractions_train.py_q050_r07_RU_211_source

48h_discovery 259 / 310 fractions_train.py_q025_r08_LU_17_source

48h_discovery 260 / 310 fractions_train.py_q010_r08_RU_137_source

48h_discovery 261 / 310 fractions_train.py_q025_r08_LU_43_source

48h_discovery 262 / 310 fractions_train.py_q010_r08_RU_211_source

48h_discovery 263 / 310 fractions_train.py_q025_r08_LU_137_source

48h_discovery 264 / 310 fractions_train.py_q025_r08_LU_101_source

48h_discovery 265 / 310 fractions_train.py_q025_r08_LU_211_source

48h_discovery 266 / 310 fractions_train.py_q025_r08_RU_101_source

48h_discovery 267 / 310 fractions_train.py_q025_r08_RU_17_source

48h_discovery 268 / 310 fractions_train.py_q025_r08_RU_137_source

48h_discovery 269 / 310 fractions_train.py_q025_r08_RU_43_source

48h_discovery 270 / 310 fractions_train.py_q050_r08_LU_17_source

48h_discovery 271 / 310 fractions_train.py_q050_r08_LU_101_source

48h_discovery 272 / 310 fractions_train.py_q050_r08_LU_43_source

48h_discovery 273 / 310 fractions_train.py_q050_r08_LU_137_source

48h_discovery 274 / 310 fractions_train.py_q050_r08_LU_211_source

48h_discovery 275 / 310 fractions_train.py_q025_r08_RU_211_source

48h_discovery 276 / 310 fractions_train.py_q050_r08_RU_17_source

48h_discovery 277 / 310 fractions_train.py_q050_r08_RU_101_source

48h_discovery 278 / 310 fractions_train.py_q050_r08_RU_43_source

48h_discovery 279 / 310 fractions_train.py_q050_r08_RU_137_source

48h_discovery 280 / 310 fractions_train.py_q010_r09_LU_17_source

48h_discovery 281 / 310 fractions_train.py_q010_r09_LU_43_source

48h_discovery 282 / 310 fractions_train.py_q010_r09_LU_137_source

48h_discovery 283 / 310 fractions_train.py_q010_r09_LU_101_source

48h_discovery 284 / 310 fractions_train.py_q050_r08_RU_211_source

48h_discovery 285 / 310 fractions_train.py_q010_r09_LU_211_source

48h_discovery 286 / 310 fractions_train.py_q010_r09_RU_17_source

48h_discovery 287 / 310 fractions_train.py_q010_r09_RU_43_source

48h_discovery 288 / 310 fractions_train.py_q025_r09_LU_17_source

48h_discovery 289 / 310 fractions_train.py_q010_r09_RU_101_source

48h_discovery 290 / 310 fractions_train.py_q010_r09_RU_137_source

48h_discovery 291 / 310 fractions_train.py_q010_r09_RU_211_source

48h_discovery 292 / 310 fractions_train.py_q025_r09_LU_43_source

48h_discovery 293 / 310 fractions_train.py_q025_r09_LU_101_source

48h_discovery 294 / 310 fractions_train.py_q025_r09_LU_137_source

48h_discovery 295 / 310 fractions_train.py_q025_r09_LU_211_source

48h_discovery 296 / 310 fractions_train.py_q025_r09_RU_43_source

48h_discovery 297 / 310 fractions_train.py_q025_r09_RU_101_source

48h_discovery 298 / 310 fractions_train.py_q025_r09_RU_17_source

48h_discovery 299 / 310 fractions_train.py_q025_r09_RU_137_source

48h_discovery 300 / 310 fractions_train.py_q050_r09_LU_17_source

48h_discovery 301 / 310 fractions_train.py_q025_r09_RU_211_source

48h_discovery 302 / 310 fractions_train.py_q050_r09_LU_43_source

48h_discovery 303 / 310 fractions_train.py_q050_r09_LU_101_source

48h_discovery 304 / 310 fractions_train.py_q050_r09_LU_137_source

48h_discovery 305 / 310 fractions_train.py_q050_r09_LU_211_source

48h_discovery 306 / 310 fractions_train.py_q050_r09_RU_43_source

48h_discovery 307 / 310 fractions_train.py_q050_r09_RU_17_source

48h_discovery 308 / 310 fractions_train.py_q050_r09_RU_101_source

48h_discovery 309 / 310 fractions_train.py_q050_r09_RU_137_source

48h_discovery 310 / 310 fractions_train.py_q050_r09_RU_211_source

In [7]:
batch([[R/'fractions/train.py',x['name'],c,s,'reader'] for x in items for c in ['LF','LU','RU'] for s in SEEDS if not(x['pct']==100 and c=='LF')], '48h_predictors')

48h_predictors jobs: 460

48h_predictors 1 / 460 fractions_train.py_q010_r00_LF_43_reader

48h_predictors 2 / 460 fractions_train.py_q010_r00_LF_101_reader

48h_predictors 3 / 460 fractions_train.py_q010_r00_LF_17_reader

48h_predictors 4 / 460 fractions_train.py_q010_r00_LF_137_reader

48h_predictors 5 / 460 fractions_train.py_q010_r00_LU_17_reader

48h_predictors 6 / 460 fractions_train.py_q010_r00_LF_211_reader

48h_predictors 7 / 460 fractions_train.py_q010_r00_LU_43_reader

48h_predictors 8 / 460 fractions_train.py_q010_r00_LU_101_reader

48h_predictors 9 / 460 fractions_train.py_q010_r00_LU_137_reader

48h_predictors 10 / 460 fractions_train.py_q010_r00_RU_17_reader

48h_predictors 11 / 460 fractions_train.py_q010_r00_RU_43_reader

48h_predictors 12 / 460 fractions_train.py_q010_r00_LU_211_reader

48h_predictors 13 / 460 fractions_train.py_q010_r00_RU_101_reader

48h_predictors 14 / 460 fractions_train.py_q010_r00_RU_137_reader

48h_predictors 15 / 460 fractions_train.py_q010_r00_RU_211_reader

48h_predictors 16 / 460 fractions_train.py_q025_r00_LF_17_reader

48h_predictors 17 / 460 fractions_train.py_q025_r00_LF_43_reader

48h_predictors 18 / 460 fractions_train.py_q025_r00_LF_101_reader

48h_predictors 19 / 460 fractions_train.py_q025_r00_LF_137_reader

48h_predictors 20 / 460 fractions_train.py_q025_r00_LU_17_reader

48h_predictors 21 / 460 fractions_train.py_q025_r00_LU_43_reader

48h_predictors 22 / 460 fractions_train.py_q025_r00_LU_101_reader

48h_predictors 23 / 460 fractions_train.py_q025_r00_LF_211_reader

48h_predictors 24 / 460 fractions_train.py_q025_r00_LU_137_reader

48h_predictors 25 / 460 fractions_train.py_q025_r00_RU_17_reader

48h_predictors 26 / 460 fractions_train.py_q025_r00_LU_211_reader

48h_predictors 27 / 460 fractions_train.py_q025_r00_RU_43_reader

48h_predictors 28 / 460 fractions_train.py_q025_r00_RU_101_reader

48h_predictors 29 / 460 fractions_train.py_q025_r00_RU_137_reader

48h_predictors 30 / 460 fractions_train.py_q025_r00_RU_211_reader

48h_predictors 31 / 460 fractions_train.py_q050_r00_LF_17_reader

48h_predictors 32 / 460 fractions_train.py_q050_r00_LF_43_reader

48h_predictors 33 / 460 fractions_train.py_q050_r00_LF_101_reader

48h_predictors 34 / 460 fractions_train.py_q050_r00_LF_137_reader

48h_predictors 35 / 460 fractions_train.py_q050_r00_LF_211_reader

48h_predictors 36 / 460 fractions_train.py_q050_r00_LU_17_reader

48h_predictors 37 / 460 fractions_train.py_q050_r00_LU_43_reader

48h_predictors 38 / 460 fractions_train.py_q050_r00_LU_137_reader

48h_predictors 39 / 460 fractions_train.py_q050_r00_LU_101_reader

48h_predictors 40 / 460 fractions_train.py_q050_r00_LU_211_reader

48h_predictors 41 / 460 fractions_train.py_q050_r00_RU_17_reader

48h_predictors 42 / 460 fractions_train.py_q050_r00_RU_101_reader

48h_predictors 43 / 460 fractions_train.py_q050_r00_RU_43_reader

48h_predictors 44 / 460 fractions_train.py_q050_r00_RU_211_reader

48h_predictors 45 / 460 fractions_train.py_q050_r00_RU_137_reader

48h_predictors 46 / 460 fractions_train.py_q100_r00_LU_17_reader

48h_predictors 47 / 460 fractions_train.py_q100_r00_LU_137_reader

48h_predictors 48 / 460 fractions_train.py_q100_r00_LU_101_reader

48h_predictors 49 / 460 fractions_train.py_q100_r00_LU_43_reader

48h_predictors 50 / 460 fractions_train.py_q100_r00_LU_211_reader

48h_predictors 51 / 460 fractions_train.py_q100_r00_RU_17_reader

48h_predictors 52 / 460 fractions_train.py_q100_r00_RU_43_reader

48h_predictors 53 / 460 fractions_train.py_q100_r00_RU_101_reader

48h_predictors 54 / 460 fractions_train.py_q010_r01_LF_17_reader

48h_predictors 55 / 460 fractions_train.py_q010_r01_LF_43_reader

48h_predictors 56 / 460 fractions_train.py_q100_r00_RU_211_reader

48h_predictors 57 / 460 fractions_train.py_q100_r00_RU_137_reader

48h_predictors 58 / 460 fractions_train.py_q010_r01_LF_137_reader

48h_predictors 59 / 460 fractions_train.py_q010_r01_LU_17_reader

48h_predictors 60 / 460 fractions_train.py_q010_r01_LF_101_reader

48h_predictors 61 / 460 fractions_train.py_q010_r01_LF_211_reader

48h_predictors 62 / 460 fractions_train.py_q010_r01_LU_43_reader

48h_predictors 63 / 460 fractions_train.py_q010_r01_LU_211_reader

48h_predictors 64 / 460 fractions_train.py_q010_r01_LU_137_reader

48h_predictors 65 / 460 fractions_train.py_q010_r01_LU_101_reader

48h_predictors 66 / 460 fractions_train.py_q010_r01_RU_43_reader

48h_predictors 67 / 460 fractions_train.py_q010_r01_RU_17_reader

48h_predictors 68 / 460 fractions_train.py_q010_r01_RU_101_reader

48h_predictors 69 / 460 fractions_train.py_q010_r01_RU_137_reader

48h_predictors 70 / 460 fractions_train.py_q010_r01_RU_211_reader

48h_predictors 71 / 460 fractions_train.py_q025_r01_LF_43_reader

48h_predictors 72 / 460 fractions_train.py_q025_r01_LF_17_reader

48h_predictors 73 / 460 fractions_train.py_q025_r01_LF_101_reader

48h_predictors 74 / 460 fractions_train.py_q025_r01_LF_137_reader

48h_predictors 75 / 460 fractions_train.py_q025_r01_LF_211_reader

48h_predictors 76 / 460 fractions_train.py_q025_r01_LU_17_reader

48h_predictors 77 / 460 fractions_train.py_q025_r01_LU_43_reader

48h_predictors 78 / 460 fractions_train.py_q025_r01_LU_101_reader

48h_predictors 79 / 460 fractions_train.py_q025_r01_LU_211_reader

48h_predictors 80 / 460 fractions_train.py_q025_r01_LU_137_reader

48h_predictors 81 / 460 fractions_train.py_q025_r01_RU_17_reader

48h_predictors 82 / 460 fractions_train.py_q025_r01_RU_43_reader

48h_predictors 83 / 460 fractions_train.py_q025_r01_RU_137_reader

48h_predictors 84 / 460 fractions_train.py_q025_r01_RU_101_reader

48h_predictors 85 / 460 fractions_train.py_q025_r01_RU_211_reader

48h_predictors 86 / 460 fractions_train.py_q050_r01_LF_17_reader

48h_predictors 87 / 460 fractions_train.py_q050_r01_LF_43_reader

48h_predictors 88 / 460 fractions_train.py_q050_r01_LF_137_reader

48h_predictors 89 / 460 fractions_train.py_q050_r01_LF_101_reader

48h_predictors 90 / 460 fractions_train.py_q050_r01_LU_17_reader

48h_predictors 91 / 460 fractions_train.py_q050_r01_LU_43_reader

48h_predictors 92 / 460 fractions_train.py_q050_r01_LU_101_reader

48h_predictors 93 / 460 fractions_train.py_q050_r01_LF_211_reader

48h_predictors 94 / 460 fractions_train.py_q050_r01_LU_137_reader

48h_predictors 95 / 460 fractions_train.py_q050_r01_RU_17_reader

48h_predictors 96 / 460 fractions_train.py_q050_r01_LU_211_reader

48h_predictors 97 / 460 fractions_train.py_q050_r01_RU_43_reader

48h_predictors 98 / 460 fractions_train.py_q050_r01_RU_137_reader

48h_predictors 99 / 460 fractions_train.py_q010_r02_LF_17_reader

48h_predictors 100 / 460 fractions_train.py_q050_r01_RU_101_reader

48h_predictors 101 / 460 fractions_train.py_q050_r01_RU_211_reader

48h_predictors 102 / 460 fractions_train.py_q010_r02_LF_43_reader

48h_predictors 103 / 460 fractions_train.py_q010_r02_LF_101_reader

48h_predictors 104 / 460 fractions_train.py_q010_r02_LF_137_reader

48h_predictors 105 / 460 fractions_train.py_q010_r02_LF_211_reader

48h_predictors 106 / 460 fractions_train.py_q010_r02_LU_17_reader

48h_predictors 107 / 460 fractions_train.py_q010_r02_LU_43_reader

48h_predictors 108 / 460 fractions_train.py_q010_r02_LU_211_reader

48h_predictors 109 / 460 fractions_train.py_q010_r02_LU_137_reader

48h_predictors 110 / 460 fractions_train.py_q010_r02_LU_101_reader

48h_predictors 111 / 460 fractions_train.py_q010_r02_RU_17_reader

48h_predictors 112 / 460 fractions_train.py_q010_r02_RU_43_reader

48h_predictors 113 / 460 fractions_train.py_q010_r02_RU_211_reader

48h_predictors 114 / 460 fractions_train.py_q010_r02_RU_101_reader

48h_predictors 115 / 460 fractions_train.py_q010_r02_RU_137_reader

48h_predictors 116 / 460 fractions_train.py_q025_r02_LF_17_reader

48h_predictors 117 / 460 fractions_train.py_q025_r02_LF_43_reader

48h_predictors 118 / 460 fractions_train.py_q025_r02_LF_101_reader

48h_predictors 119 / 460 fractions_train.py_q025_r02_LF_137_reader

48h_predictors 120 / 460 fractions_train.py_q025_r02_LF_211_reader

48h_predictors 121 / 460 fractions_train.py_q025_r02_LU_17_reader

48h_predictors 122 / 460 fractions_train.py_q025_r02_LU_43_reader

48h_predictors 123 / 460 fractions_train.py_q025_r02_LU_101_reader

48h_predictors 124 / 460 fractions_train.py_q025_r02_LU_137_reader

48h_predictors 125 / 460 fractions_train.py_q025_r02_RU_17_reader

48h_predictors 126 / 460 fractions_train.py_q025_r02_LU_211_reader

48h_predictors 127 / 460 fractions_train.py_q025_r02_RU_43_reader

48h_predictors 128 / 460 fractions_train.py_q025_r02_RU_101_reader

48h_predictors 129 / 460 fractions_train.py_q025_r02_RU_137_reader

48h_predictors 130 / 460 fractions_train.py_q025_r02_RU_211_reader

48h_predictors 131 / 460 fractions_train.py_q050_r02_LF_17_reader

48h_predictors 132 / 460 fractions_train.py_q050_r02_LF_43_reader

48h_predictors 133 / 460 fractions_train.py_q050_r02_LF_137_reader

48h_predictors 134 / 460 fractions_train.py_q050_r02_LF_101_reader

48h_predictors 135 / 460 fractions_train.py_q050_r02_LF_211_reader

48h_predictors 136 / 460 fractions_train.py_q050_r02_LU_17_reader

48h_predictors 137 / 460 fractions_train.py_q050_r02_LU_101_reader

48h_predictors 138 / 460 fractions_train.py_q050_r02_LU_43_reader

48h_predictors 139 / 460 fractions_train.py_q050_r02_LU_137_reader

48h_predictors 140 / 460 fractions_train.py_q050_r02_LU_211_reader

48h_predictors 141 / 460 fractions_train.py_q050_r02_RU_43_reader

48h_predictors 142 / 460 fractions_train.py_q050_r02_RU_17_reader

48h_predictors 143 / 460 fractions_train.py_q050_r02_RU_101_reader

48h_predictors 144 / 460 fractions_train.py_q050_r02_RU_137_reader

48h_predictors 145 / 460 fractions_train.py_q010_r03_LF_43_reader

48h_predictors 146 / 460 fractions_train.py_q010_r03_LF_17_reader

48h_predictors 147 / 460 fractions_train.py_q050_r02_RU_211_reader

48h_predictors 148 / 460 fractions_train.py_q010_r03_LF_101_reader

48h_predictors 149 / 460 fractions_train.py_q010_r03_LU_17_reader

48h_predictors 150 / 460 fractions_train.py_q010_r03_LF_211_reader

48h_predictors 151 / 460 fractions_train.py_q010_r03_LF_137_reader

48h_predictors 152 / 460 fractions_train.py_q010_r03_LU_137_reader

48h_predictors 153 / 460 fractions_train.py_q010_r03_LU_43_reader

48h_predictors 154 / 460 fractions_train.py_q010_r03_LU_101_reader

48h_predictors 155 / 460 fractions_train.py_q010_r03_LU_211_reader

48h_predictors 156 / 460 fractions_train.py_q010_r03_RU_17_reader

48h_predictors 157 / 460 fractions_train.py_q010_r03_RU_43_reader

48h_predictors 158 / 460 fractions_train.py_q010_r03_RU_101_reader

48h_predictors 159 / 460 fractions_train.py_q010_r03_RU_137_reader

48h_predictors 160 / 460 fractions_train.py_q010_r03_RU_211_reader

48h_predictors 161 / 460 fractions_train.py_q025_r03_LF_17_reader

48h_predictors 162 / 460 fractions_train.py_q025_r03_LF_43_reader

48h_predictors 163 / 460 fractions_train.py_q025_r03_LF_137_reader

48h_predictors 164 / 460 fractions_train.py_q025_r03_LF_101_reader

48h_predictors 165 / 460 fractions_train.py_q025_r03_LU_17_reader

48h_predictors 166 / 460 fractions_train.py_q025_r03_LU_43_reader

48h_predictors 167 / 460 fractions_train.py_q025_r03_LF_211_reader

48h_predictors 168 / 460 fractions_train.py_q025_r03_LU_101_reader

48h_predictors 169 / 460 fractions_train.py_q025_r03_LU_137_reader

48h_predictors 170 / 460 fractions_train.py_q025_r03_RU_17_reader

48h_predictors 171 / 460 fractions_train.py_q025_r03_RU_43_reader

48h_predictors 172 / 460 fractions_train.py_q025_r03_LU_211_reader

48h_predictors 173 / 460 fractions_train.py_q025_r03_RU_101_reader

48h_predictors 174 / 460 fractions_train.py_q025_r03_RU_137_reader

48h_predictors 175 / 460 fractions_train.py_q025_r03_RU_211_reader

48h_predictors 176 / 460 fractions_train.py_q050_r03_LF_17_reader

48h_predictors 177 / 460 fractions_train.py_q050_r03_LF_43_reader

48h_predictors 178 / 460 fractions_train.py_q050_r03_LF_211_reader

48h_predictors 179 / 460 fractions_train.py_q050_r03_LF_101_reader

48h_predictors 180 / 460 fractions_train.py_q050_r03_LU_17_reader

48h_predictors 181 / 460 fractions_train.py_q050_r03_LF_137_reader

48h_predictors 182 / 460 fractions_train.py_q050_r03_LU_101_reader

48h_predictors 183 / 460 fractions_train.py_q050_r03_LU_43_reader

48h_predictors 184 / 460 fractions_train.py_q050_r03_LU_137_reader

48h_predictors 185 / 460 fractions_train.py_q050_r03_LU_211_reader

48h_predictors 186 / 460 fractions_train.py_q050_r03_RU_17_reader

48h_predictors 187 / 460 fractions_train.py_q050_r03_RU_43_reader

48h_predictors 188 / 460 fractions_train.py_q050_r03_RU_137_reader

48h_predictors 189 / 460 fractions_train.py_q050_r03_RU_101_reader

48h_predictors 190 / 460 fractions_train.py_q050_r03_RU_211_reader

48h_predictors 191 / 460 fractions_train.py_q010_r04_LF_17_reader

48h_predictors 192 / 460 fractions_train.py_q010_r04_LF_43_reader

48h_predictors 193 / 460 fractions_train.py_q010_r04_LF_101_reader

48h_predictors 194 / 460 fractions_train.py_q010_r04_LF_137_reader

48h_predictors 195 / 460 fractions_train.py_q010_r04_LF_211_reader

48h_predictors 196 / 460 fractions_train.py_q010_r04_LU_43_reader

48h_predictors 197 / 460 fractions_train.py_q010_r04_LU_17_reader

48h_predictors 198 / 460 fractions_train.py_q010_r04_LU_101_reader

48h_predictors 199 / 460 fractions_train.py_q010_r04_LU_137_reader

48h_predictors 200 / 460 fractions_train.py_q010_r04_RU_17_reader

48h_predictors 201 / 460 fractions_train.py_q010_r04_LU_211_reader

48h_predictors 202 / 460 fractions_train.py_q010_r04_RU_43_reader

48h_predictors 203 / 460 fractions_train.py_q010_r04_RU_101_reader

48h_predictors 204 / 460 fractions_train.py_q010_r04_RU_137_reader

48h_predictors 205 / 460 fractions_train.py_q025_r04_LF_17_reader

48h_predictors 206 / 460 fractions_train.py_q010_r04_RU_211_reader

48h_predictors 207 / 460 fractions_train.py_q025_r04_LF_43_reader

48h_predictors 208 / 460 fractions_train.py_q025_r04_LF_101_reader

48h_predictors 209 / 460 fractions_train.py_q025_r04_LF_211_reader

48h_predictors 210 / 460 fractions_train.py_q025_r04_LF_137_reader

48h_predictors 211 / 460 fractions_train.py_q025_r04_LU_17_reader

48h_predictors 212 / 460 fractions_train.py_q025_r04_LU_43_reader

48h_predictors 213 / 460 fractions_train.py_q025_r04_LU_137_reader

48h_predictors 214 / 460 fractions_train.py_q025_r04_LU_101_reader

48h_predictors 215 / 460 fractions_train.py_q025_r04_LU_211_reader

48h_predictors 216 / 460 fractions_train.py_q025_r04_RU_43_reader

48h_predictors 217 / 460 fractions_train.py_q025_r04_RU_17_reader

48h_predictors 218 / 460 fractions_train.py_q025_r04_RU_101_reader

48h_predictors 219 / 460 fractions_train.py_q025_r04_RU_211_reader

48h_predictors 220 / 460 fractions_train.py_q025_r04_RU_137_reader

48h_predictors 221 / 460 fractions_train.py_q050_r04_LF_17_reader

48h_predictors 222 / 460 fractions_train.py_q050_r04_LF_43_reader

48h_predictors 223 / 460 fractions_train.py_q050_r04_LF_101_reader

48h_predictors 224 / 460 fractions_train.py_q050_r04_LU_17_reader

48h_predictors 225 / 460 fractions_train.py_q050_r04_LF_211_reader

48h_predictors 226 / 460 fractions_train.py_q050_r04_LF_137_reader

48h_predictors 227 / 460 fractions_train.py_q050_r04_LU_43_reader

48h_predictors 228 / 460 fractions_train.py_q050_r04_LU_137_reader

48h_predictors 229 / 460 fractions_train.py_q050_r04_LU_101_reader

48h_predictors 230 / 460 fractions_train.py_q050_r04_LU_211_reader

48h_predictors 231 / 460 fractions_train.py_q050_r04_RU_17_reader

48h_predictors 232 / 460 fractions_train.py_q050_r04_RU_101_reader

48h_predictors 233 / 460 fractions_train.py_q050_r04_RU_43_reader

48h_predictors 234 / 460 fractions_train.py_q050_r04_RU_137_reader

48h_predictors 235 / 460 fractions_train.py_q050_r04_RU_211_reader

48h_predictors 236 / 460 fractions_train.py_q010_r05_LF_17_reader

48h_predictors 237 / 460 fractions_train.py_q010_r05_LF_43_reader

48h_predictors 238 / 460 fractions_train.py_q010_r05_LF_101_reader

48h_predictors 239 / 460 fractions_train.py_q010_r05_LF_211_reader

48h_predictors 240 / 460 fractions_train.py_q010_r05_LU_17_reader

48h_predictors 241 / 460 fractions_train.py_q010_r05_LF_137_reader

48h_predictors 242 / 460 fractions_train.py_q010_r05_LU_43_reader

48h_predictors 243 / 460 fractions_train.py_q010_r05_LU_211_reader

48h_predictors 244 / 460 fractions_train.py_q010_r05_LU_137_reader

48h_predictors 245 / 460 fractions_train.py_q010_r05_LU_101_reader

48h_predictors 246 / 460 fractions_train.py_q010_r05_RU_17_reader

48h_predictors 247 / 460 fractions_train.py_q010_r05_RU_101_reader

48h_predictors 248 / 460 fractions_train.py_q010_r05_RU_137_reader

48h_predictors 249 / 460 fractions_train.py_q010_r05_RU_43_reader

48h_predictors 250 / 460 fractions_train.py_q010_r05_RU_211_reader

48h_predictors 251 / 460 fractions_train.py_q025_r05_LF_101_reader

48h_predictors 252 / 460 fractions_train.py_q025_r05_LF_17_reader

48h_predictors 253 / 460 fractions_train.py_q025_r05_LF_43_reader

48h_predictors 254 / 460 fractions_train.py_q025_r05_LF_137_reader

48h_predictors 255 / 460 fractions_train.py_q025_r05_LU_17_reader

48h_predictors 256 / 460 fractions_train.py_q025_r05_LF_211_reader

48h_predictors 257 / 460 fractions_train.py_q025_r05_LU_43_reader

48h_predictors 258 / 460 fractions_train.py_q025_r05_LU_101_reader

48h_predictors 259 / 460 fractions_train.py_q025_r05_RU_17_reader

48h_predictors 260 / 460 fractions_train.py_q025_r05_RU_43_reader

48h_predictors 261 / 460 fractions_train.py_q025_r05_LU_211_reader

48h_predictors 262 / 460 fractions_train.py_q025_r05_LU_137_reader

48h_predictors 263 / 460 fractions_train.py_q025_r05_RU_101_reader

48h_predictors 264 / 460 fractions_train.py_q025_r05_RU_137_reader

48h_predictors 265 / 460 fractions_train.py_q025_r05_RU_211_reader

48h_predictors 266 / 460 fractions_train.py_q050_r05_LF_17_reader

48h_predictors 267 / 460 fractions_train.py_q050_r05_LF_101_reader

48h_predictors 268 / 460 fractions_train.py_q050_r05_LF_43_reader

48h_predictors 269 / 460 fractions_train.py_q050_r05_LF_137_reader

48h_predictors 270 / 460 fractions_train.py_q050_r05_LU_101_reader

48h_predictors 271 / 460 fractions_train.py_q050_r05_LU_17_reader

48h_predictors 272 / 460 fractions_train.py_q050_r05_LU_43_reader

48h_predictors 273 / 460 fractions_train.py_q050_r05_LF_211_reader

48h_predictors 274 / 460 fractions_train.py_q050_r05_LU_137_reader

48h_predictors 275 / 460 fractions_train.py_q050_r05_RU_17_reader

48h_predictors 276 / 460 fractions_train.py_q050_r05_RU_43_reader

48h_predictors 277 / 460 fractions_train.py_q050_r05_LU_211_reader

48h_predictors 278 / 460 fractions_train.py_q050_r05_RU_101_reader

48h_predictors 279 / 460 fractions_train.py_q050_r05_RU_137_reader

48h_predictors 280 / 460 fractions_train.py_q050_r05_RU_211_reader

48h_predictors 281 / 460 fractions_train.py_q010_r06_LF_17_reader

48h_predictors 282 / 460 fractions_train.py_q010_r06_LF_43_reader

48h_predictors 283 / 460 fractions_train.py_q010_r06_LF_101_reader

48h_predictors 284 / 460 fractions_train.py_q010_r06_LF_137_reader

48h_predictors 285 / 460 fractions_train.py_q010_r06_LF_211_reader

48h_predictors 286 / 460 fractions_train.py_q010_r06_LU_101_reader

48h_predictors 287 / 460 fractions_train.py_q010_r06_LU_17_reader

48h_predictors 288 / 460 fractions_train.py_q010_r06_LU_43_reader

48h_predictors 289 / 460 fractions_train.py_q010_r06_LU_137_reader

48h_predictors 290 / 460 fractions_train.py_q010_r06_RU_43_reader

48h_predictors 291 / 460 fractions_train.py_q010_r06_RU_17_reader

48h_predictors 292 / 460 fractions_train.py_q010_r06_RU_101_reader

48h_predictors 293 / 460 fractions_train.py_q010_r06_LU_211_reader

48h_predictors 294 / 460 fractions_train.py_q010_r06_RU_137_reader

48h_predictors 295 / 460 fractions_train.py_q010_r06_RU_211_reader

48h_predictors 296 / 460 fractions_train.py_q025_r06_LF_17_reader

48h_predictors 297 / 460 fractions_train.py_q025_r06_LF_43_reader

48h_predictors 298 / 460 fractions_train.py_q025_r06_LF_101_reader

48h_predictors 299 / 460 fractions_train.py_q025_r06_LU_17_reader

48h_predictors 300 / 460 fractions_train.py_q025_r06_LF_137_reader

48h_predictors 301 / 460 fractions_train.py_q025_r06_LF_211_reader

48h_predictors 302 / 460 fractions_train.py_q025_r06_LU_43_reader

48h_predictors 303 / 460 fractions_train.py_q025_r06_LU_137_reader

48h_predictors 304 / 460 fractions_train.py_q025_r06_LU_101_reader

48h_predictors 305 / 460 fractions_train.py_q025_r06_LU_211_reader

48h_predictors 306 / 460 fractions_train.py_q025_r06_RU_17_reader

48h_predictors 307 / 460 fractions_train.py_q025_r06_RU_101_reader

48h_predictors 308 / 460 fractions_train.py_q025_r06_RU_43_reader

48h_predictors 309 / 460 fractions_train.py_q025_r06_RU_137_reader

48h_predictors 310 / 460 fractions_train.py_q050_r06_LF_17_reader

48h_predictors 311 / 460 fractions_train.py_q050_r06_LF_43_reader

48h_predictors 312 / 460 fractions_train.py_q025_r06_RU_211_reader

48h_predictors 313 / 460 fractions_train.py_q050_r06_LF_101_reader

48h_predictors 314 / 460 fractions_train.py_q050_r06_LF_137_reader

48h_predictors 315 / 460 fractions_train.py_q050_r06_LF_211_reader

48h_predictors 316 / 460 fractions_train.py_q050_r06_LU_17_reader

48h_predictors 317 / 460 fractions_train.py_q050_r06_LU_43_reader

48h_predictors 318 / 460 fractions_train.py_q050_r06_LU_101_reader

48h_predictors 319 / 460 fractions_train.py_q050_r06_LU_137_reader

48h_predictors 320 / 460 fractions_train.py_q050_r06_LU_211_reader

48h_predictors 321 / 460 fractions_train.py_q050_r06_RU_43_reader

48h_predictors 322 / 460 fractions_train.py_q050_r06_RU_17_reader

48h_predictors 323 / 460 fractions_train.py_q050_r06_RU_101_reader

48h_predictors 324 / 460 fractions_train.py_q050_r06_RU_137_reader

48h_predictors 325 / 460 fractions_train.py_q050_r06_RU_211_reader

48h_predictors 326 / 460 fractions_train.py_q010_r07_LF_43_reader

48h_predictors 327 / 460 fractions_train.py_q010_r07_LF_101_reader

48h_predictors 328 / 460 fractions_train.py_q010_r07_LF_17_reader

48h_predictors 329 / 460 fractions_train.py_q010_r07_LF_137_reader

48h_predictors 330 / 460 fractions_train.py_q010_r07_LF_211_reader

48h_predictors 331 / 460 fractions_train.py_q010_r07_LU_43_reader

48h_predictors 332 / 460 fractions_train.py_q010_r07_LU_17_reader

48h_predictors 333 / 460 fractions_train.py_q010_r07_LU_101_reader

48h_predictors 334 / 460 fractions_train.py_q010_r07_LU_137_reader

48h_predictors 335 / 460 fractions_train.py_q010_r07_RU_17_reader

48h_predictors 336 / 460 fractions_train.py_q010_r07_LU_211_reader

48h_predictors 337 / 460 fractions_train.py_q010_r07_RU_43_reader

48h_predictors 338 / 460 fractions_train.py_q010_r07_RU_101_reader

48h_predictors 339 / 460 fractions_train.py_q010_r07_RU_137_reader

48h_predictors 340 / 460 fractions_train.py_q010_r07_RU_211_reader

48h_predictors 341 / 460 fractions_train.py_q025_r07_LF_43_reader

48h_predictors 342 / 460 fractions_train.py_q025_r07_LF_17_reader

48h_predictors 343 / 460 fractions_train.py_q025_r07_LF_101_reader

48h_predictors 344 / 460 fractions_train.py_q025_r07_LF_137_reader

48h_predictors 345 / 460 fractions_train.py_q025_r07_LU_17_reader

48h_predictors 346 / 460 fractions_train.py_q025_r07_LU_43_reader

48h_predictors 347 / 460 fractions_train.py_q025_r07_LU_101_reader

48h_predictors 348 / 460 fractions_train.py_q025_r07_LF_211_reader

48h_predictors 349 / 460 fractions_train.py_q025_r07_LU_137_reader

48h_predictors 350 / 460 fractions_train.py_q025_r07_RU_43_reader

48h_predictors 351 / 460 fractions_train.py_q025_r07_LU_211_reader

48h_predictors 352 / 460 fractions_train.py_q025_r07_RU_17_reader

48h_predictors 353 / 460 fractions_train.py_q025_r07_RU_101_reader

48h_predictors 354 / 460 fractions_train.py_q025_r07_RU_137_reader

48h_predictors 355 / 460 fractions_train.py_q025_r07_RU_211_reader

48h_predictors 356 / 460 fractions_train.py_q050_r07_LF_17_reader

48h_predictors 357 / 460 fractions_train.py_q050_r07_LF_101_reader

48h_predictors 358 / 460 fractions_train.py_q050_r07_LF_137_reader

48h_predictors 359 / 460 fractions_train.py_q050_r07_LF_43_reader

48h_predictors 360 / 460 fractions_train.py_q050_r07_LU_17_reader

48h_predictors 361 / 460 fractions_train.py_q050_r07_LF_211_reader

48h_predictors 362 / 460 fractions_train.py_q050_r07_LU_43_reader

48h_predictors 363 / 460 fractions_train.py_q050_r07_LU_101_reader

48h_predictors 364 / 460 fractions_train.py_q050_r07_RU_43_reader

48h_predictors 365 / 460 fractions_train.py_q050_r07_LU_211_reader

48h_predictors 366 / 460 fractions_train.py_q050_r07_LU_137_reader

48h_predictors 367 / 460 fractions_train.py_q050_r07_RU_17_reader

48h_predictors 368 / 460 fractions_train.py_q050_r07_RU_101_reader

48h_predictors 369 / 460 fractions_train.py_q050_r07_RU_211_reader

48h_predictors 370 / 460 fractions_train.py_q050_r07_RU_137_reader

48h_predictors 371 / 460 fractions_train.py_q010_r08_LF_17_reader

48h_predictors 372 / 460 fractions_train.py_q010_r08_LF_211_reader

48h_predictors 373 / 460 fractions_train.py_q010_r08_LF_101_reader

48h_predictors 374 / 460 fractions_train.py_q010_r08_LF_43_reader

48h_predictors 375 / 460 fractions_train.py_q010_r08_LF_137_reader

48h_predictors 376 / 460 fractions_train.py_q010_r08_LU_17_reader

48h_predictors 377 / 460 fractions_train.py_q010_r08_LU_43_reader

48h_predictors 378 / 460 fractions_train.py_q010_r08_LU_101_reader

48h_predictors 379 / 460 fractions_train.py_q010_r08_LU_211_reader

48h_predictors 380 / 460 fractions_train.py_q010_r08_LU_137_reader

48h_predictors 381 / 460 fractions_train.py_q010_r08_RU_17_reader

48h_predictors 382 / 460 fractions_train.py_q010_r08_RU_43_reader

48h_predictors 383 / 460 fractions_train.py_q010_r08_RU_137_reader

48h_predictors 384 / 460 fractions_train.py_q010_r08_RU_101_reader

48h_predictors 385 / 460 fractions_train.py_q010_r08_RU_211_reader

48h_predictors 386 / 460 fractions_train.py_q025_r08_LF_17_reader

48h_predictors 387 / 460 fractions_train.py_q025_r08_LF_43_reader

48h_predictors 388 / 460 fractions_train.py_q025_r08_LF_101_reader

48h_predictors 389 / 460 fractions_train.py_q025_r08_LF_137_reader

48h_predictors 390 / 460 fractions_train.py_q025_r08_LF_211_reader

48h_predictors 391 / 460 fractions_train.py_q025_r08_LU_43_reader

48h_predictors 392 / 460 fractions_train.py_q025_r08_LU_17_reader

48h_predictors 393 / 460 fractions_train.py_q025_r08_LU_101_reader

48h_predictors 394 / 460 fractions_train.py_q025_r08_LU_137_reader

48h_predictors 395 / 460 fractions_train.py_q025_r08_RU_43_reader

48h_predictors 396 / 460 fractions_train.py_q025_r08_RU_17_reader

48h_predictors 397 / 460 fractions_train.py_q025_r08_RU_101_reader

48h_predictors 398 / 460 fractions_train.py_q025_r08_LU_211_reader

48h_predictors 399 / 460 fractions_train.py_q025_r08_RU_137_reader

48h_predictors 400 / 460 fractions_train.py_q050_r08_LF_17_reader

48h_predictors 401 / 460 fractions_train.py_q050_r08_LF_43_reader

48h_predictors 402 / 460 fractions_train.py_q050_r08_LF_101_reader

48h_predictors 403 / 460 fractions_train.py_q025_r08_RU_211_reader

48h_predictors 404 / 460 fractions_train.py_q050_r08_LU_43_reader

48h_predictors 405 / 460 fractions_train.py_q050_r08_LU_17_reader

48h_predictors 406 / 460 fractions_train.py_q050_r08_LF_211_reader

48h_predictors 407 / 460 fractions_train.py_q050_r08_LF_137_reader

48h_predictors 408 / 460 fractions_train.py_q050_r08_LU_101_reader

48h_predictors 409 / 460 fractions_train.py_q050_r08_RU_17_reader

48h_predictors 410 / 460 fractions_train.py_q050_r08_LU_211_reader

48h_predictors 411 / 460 fractions_train.py_q050_r08_LU_137_reader

48h_predictors 412 / 460 fractions_train.py_q050_r08_RU_43_reader

48h_predictors 413 / 460 fractions_train.py_q050_r08_RU_101_reader

48h_predictors 414 / 460 fractions_train.py_q050_r08_RU_211_reader

48h_predictors 415 / 460 fractions_train.py_q050_r08_RU_137_reader

48h_predictors 416 / 460 fractions_train.py_q010_r09_LF_17_reader

48h_predictors 417 / 460 fractions_train.py_q010_r09_LF_43_reader

48h_predictors 418 / 460 fractions_train.py_q010_r09_LF_101_reader

48h_predictors 419 / 460 fractions_train.py_q010_r09_LF_137_reader

48h_predictors 420 / 460 fractions_train.py_q010_r09_LU_17_reader

48h_predictors 421 / 460 fractions_train.py_q010_r09_LF_211_reader

48h_predictors 422 / 460 fractions_train.py_q010_r09_LU_101_reader

48h_predictors 423 / 460 fractions_train.py_q010_r09_LU_137_reader

48h_predictors 424 / 460 fractions_train.py_q010_r09_LU_43_reader

48h_predictors 425 / 460 fractions_train.py_q010_r09_LU_211_reader

48h_predictors 426 / 460 fractions_train.py_q010_r09_RU_17_reader

48h_predictors 427 / 460 fractions_train.py_q010_r09_RU_43_reader

48h_predictors 428 / 460 fractions_train.py_q010_r09_RU_101_reader

48h_predictors 429 / 460 fractions_train.py_q010_r09_RU_137_reader

48h_predictors 430 / 460 fractions_train.py_q010_r09_RU_211_reader

48h_predictors 431 / 460 fractions_train.py_q025_r09_LF_17_reader

48h_predictors 432 / 460 fractions_train.py_q025_r09_LF_43_reader

48h_predictors 433 / 460 fractions_train.py_q025_r09_LF_211_reader

48h_predictors 434 / 460 fractions_train.py_q025_r09_LF_137_reader

48h_predictors 435 / 460 fractions_train.py_q025_r09_LF_101_reader

48h_predictors 436 / 460 fractions_train.py_q025_r09_LU_17_reader

48h_predictors 437 / 460 fractions_train.py_q025_r09_LU_43_reader

48h_predictors 438 / 460 fractions_train.py_q025_r09_LU_101_reader

48h_predictors 439 / 460 fractions_train.py_q025_r09_LU_137_reader

48h_predictors 440 / 460 fractions_train.py_q025_r09_LU_211_reader

48h_predictors 441 / 460 fractions_train.py_q025_r09_RU_17_reader

48h_predictors 442 / 460 fractions_train.py_q025_r09_RU_43_reader

48h_predictors 443 / 460 fractions_train.py_q025_r09_RU_211_reader

48h_predictors 444 / 460 fractions_train.py_q025_r09_RU_101_reader

48h_predictors 445 / 460 fractions_train.py_q025_r09_RU_137_reader

48h_predictors 446 / 460 fractions_train.py_q050_r09_LF_17_reader

48h_predictors 447 / 460 fractions_train.py_q050_r09_LF_43_reader

48h_predictors 448 / 460 fractions_train.py_q050_r09_LF_137_reader

48h_predictors 449 / 460 fractions_train.py_q050_r09_LF_211_reader

48h_predictors 450 / 460 fractions_train.py_q050_r09_LU_17_reader

48h_predictors 451 / 460 fractions_train.py_q050_r09_LF_101_reader

48h_predictors 452 / 460 fractions_train.py_q050_r09_LU_43_reader

48h_predictors 453 / 460 fractions_train.py_q050_r09_LU_101_reader

48h_predictors 454 / 460 fractions_train.py_q050_r09_LU_137_reader

48h_predictors 455 / 460 fractions_train.py_q050_r09_LU_211_reader

48h_predictors 456 / 460 fractions_train.py_q050_r09_RU_43_reader

48h_predictors 457 / 460 fractions_train.py_q050_r09_RU_17_reader

48h_predictors 458 / 460 fractions_train.py_q050_r09_RU_101_reader

48h_predictors 459 / 460 fractions_train.py_q050_r09_RU_137_reader

48h_predictors 460 / 460 fractions_train.py_q050_r09_RU_211_reader

In [2]:
items=json.loads((R/'fractions/subsets.json').read_text())
batch([[R/'fractions/baselines.py',R/'fractions/subsets'/x['name']] for x in items if x['pct']!=100], 'fraction_baselines')

fraction_baselines jobs: 30

fraction_baselines 1 / 30 baselines_q010_r01

fraction_baselines 2 / 30 baselines_q010_r00

fraction_baselines 3 / 30 baselines_q025_r00

fraction_baselines 4 / 30 baselines_q050_r00

fraction_baselines 5 / 30 baselines_q010_r02

fraction_baselines 6 / 30 baselines_q025_r01

fraction_baselines 7 / 30 baselines_q025_r02

fraction_baselines 8 / 30 baselines_q050_r01

fraction_baselines 9 / 30 baselines_q010_r03

fraction_baselines 10 / 30 baselines_q050_r02

fraction_baselines 11 / 30 baselines_q025_r03

fraction_baselines 12 / 30 baselines_q010_r04

fraction_baselines 13 / 30 baselines_q050_r03

fraction_baselines 14 / 30 baselines_q010_r05

fraction_baselines 15 / 30 baselines_q025_r04

fraction_baselines 16 / 30 baselines_q050_r04

fraction_baselines 17 / 30 baselines_q025_r05

fraction_baselines 18 / 30 baselines_q010_r06

fraction_baselines 19 / 30 baselines_q050_r05

fraction_baselines 20 / 30 baselines_q025_r06

fraction_baselines 21 / 30 baselines_q050_r06

fraction_baselines 22 / 30 baselines_q010_r07

fraction_baselines 23 / 30 baselines_q010_r08

fraction_baselines 24 / 30 baselines_q025_r07

fraction_baselines 25 / 30 baselines_q050_r07

fraction_baselines 26 / 30 baselines_q025_r08

fraction_baselines 27 / 30 baselines_q010_r09

fraction_baselines 28 / 30 baselines_q050_r08

fraction_baselines 29 / 30 baselines_q025_r09

fraction_baselines 30 / 30 baselines_q050_r09

In [3]:
run([R/'fractions/evaluate.py'])
import pandas as pd
metrics=pd.read_json(R/'fractions/evaluation/metrics.json')
display(metrics.groupby(['pct','model']).mse.mean().unstack())
display(pd.read_json(R/'fractions/evaluation/contrasts.json'))
(R/'status.json').write_text(json.dumps(dict(phase='complete',updated=time.time())))

model        LF        LU        RU  constant        rf     ridge       xgb
pct
10     0.072202  0.086420  0.238181  0.679052  0.385685  0.318932  0.344440
25     0.056405  0.059474  0.083960  0.674796  0.264268  0.222653  0.229873
50     0.049490  0.047817  0.054620  0.673173  0.156442  0.191673  0.191764
100    0.046369  0.042817  0.045169  0.672369  0.072455  0.180015  0.178505

,pct,contrast,family,size,difference,interval
0,10,strategy,primary,4,-0.165980,"[-0.19071598902574802, -0.143281806465928]"
1,10,updated_source,secondary,20,-0.151762,"[-0.18074927553851503, -0.126171510390116]"
2,10,learned_update,secondary,20,0.014218,"[0.010548823081750001, 0.018246328089285002]"
3,10,ridge,baseline,12,-0.246731,"[-0.29468665658283805, -0.20268438100840502]"
4,10,rf,baseline,12,-0.313483,"[-0.37649322616164504, -0.25412198982536904]"
5,10,xgb,baseline,12,-0.272238,"[-0.313739308888609, -0.233496675025043]"
6,25,strategy,primary,4,-0.027556,"[-0.033823751548444005, -0.021742717329817002]"
7,25,updated_source,secondary,20,-0.024486,"[-0.031475860945186, -0.01833988123823]"
8,25,learned_update,secondary,20,0.003070,"[0.000310091779325, 0.005953370656867]"
9,25,ridge,baseline,12,-0.166248,"[-0.201535742951742, -0.13551957179513102]"
10,25,rf,baseline,12,-0.207863,"[-0.24951609133416303, -0.16858560397886202]"
11,25,xgb,baseline,12,-0.173468,"[-0.20922632423075402, -0.142419459382836]"
12,50,strategy,primary,4,-0.005130,"[-0.009472756991935, -0.0013628264207640002]"
13,50,updated_source,secondary,20,-0.006803,"[-0.011108002492704001, -0.0035136077360380003]"
14,50,learned_update,secondary,20,-0.001672,"[-0.005086662407367, 0.0014663731958450001]"
15,50,ridge,baseline,12,-0.142184,"[-0.17568845787727103, -0.113351669438795]"
16,50,rf,baseline,12,-0.106953,"[-0.13529501169122202, -0.080909334359009]"
17,50,xgb,baseline,12,-0.142275,"[-0.17438405106731703, -0.11388622152629001]"
18,100,strategy,primary,4,0.001200,"[-0.002403774891966, 0.00439710704299]"
19,100,updated_source,secondary,20,-0.002352,"[-0.005611359668449001, 1.0872684844575731e-05]"
20,100,learned_update,secondary,20,-0.003552,"[-0.006681091623294001, -0.000603426184392]"
21,100,ridge,baseline,12,-0.133646,"[-0.16713639063939, -0.104203515068973]"
22,100,rf,baseline,12,-0.026086,"[-0.044653288610924005, -0.010216114603222]"
23,100,xgb,baseline,12,-0.132136,"[-0.16468741345865, -0.10347328241491201]"

52